basePath: /matrix
definitions:
  enum.MatrixType:
    enum:
    - Q
    - R
    - Rotated
    type: string
    x-enum-varnames:
    - Q
    - R
    - Rotated
  models.MatrixResult:
    properties:
      stats:
        $ref: '#/definitions/models.MatrixStats'
      type:
        $ref: '#/definitions/enum.MatrixType'
      value:
        items:
          items:
            type: number
          type: array
        type: array
    type: object
  models.MatrixStats:
    properties:
      avg:
        type: number
      is_diagonal:
        type: boolean
      max:
        type: number
      min:
        type: number
      sum:
        type: number
    type: object
  models.QRResponse:
    properties:
      results:
        items:
          $ref: '#/definitions/models.MatrixResult'
        type: array
    type: object
  models.Request:
    properties:
      matrix:
        items:
          items:
            type: number
          type: array
        type: array
      with_statistics:
        description: 'required: false'
        type: boolean
    type: object
  models.RotateResponse:
    properties:
      degrees:
        type: integer
      results:
        items:
          $ref: '#/definitions/models.MatrixResult'
        type: array
    type: object
  models.RotationRequest:
    properties:
      degrees:
        type: integer
      matrix:
        items:
          items:
            type: number
          type: array
        type: array
      with_statistics:
        description: 'required: false'
        type: boolean
    type: object
host: localhost:8080
info:
  contact: {}
  description: API de operaciones sobre matrices.
  title: Go API
  version: "1.0"
paths:
  /matrix/factorize:
    post:
      consumes:
      - application/json
      description: Recibe una matriz y retorna dos matrices Q y R
      operationId: factorize-matrix
      parameters:
      - description: Solicitud
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/models.Request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.QRResponse'
      summary: Factorial QR de una matriz
  /matrix/rotate:
    post:
      consumes:
      - application/json
      description: Recibe una matriz y una cantidad de grados de giro (múltiplos de
        90) y retorna la matriz rotada dicha cantidad de grados
      operationId: rotate-matrix
      parameters:
      - description: Solicitud
        in: body
        name: RotationRequest
        required: true
        schema:
          $ref: '#/definitions/models.RotationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.RotateResponse'
      summary: Rota una matriz
swagger: "2.0"
